package kubebuild

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"
)

// GoFile имя сгенерированного Go-файла в пакете со схемами
const GoFile = "zz_generated.crd.go"

// goFileFormat версия шаблона Go-файла, при её смене файл перегенерируется
const goFileFormat = 2

// goFileMarker строка, по которой определяется версия шаблона
const goFileMarker = "//crd:format "

var goFileTemplate = template.Must(template.New("gofile").Parse(`// Code generated by {{.Tool}}. DO NOT EDIT.

//crd:format {{.Format}}

// Package {{.Package}} содержит снимки схем типов, собранные {{.Tool}}
//
// Подключение в приложении:
//
//	func init() {
//		crd.SetDERSource({{.Package}}.FS())
//	}
package {{.Package}}

import (
	"embed"
	"io/fs"
)

//go:embed {{.Data}}
var data embed.FS

// FS возвращает каталог со снимками схем
func FS() fs.FS {
	// fs.Sub возвращает ошибку только для некорректного пути, а путь здесь постоянный
	sub, _ := fs.Sub(data, "{{.Data}}")
	return sub
}
`))

// ensureGoFile создаёт Go-файл пакета, если его нет или он другой версии
func ensureGoFile(dir, tool string) (bool, error) {
	file := filepath.Join(dir, GoFile)
	cur, err := os.ReadFile(file)
	if err == nil && goFileVersion(cur) == goFileFormat {
		return false, nil
	}
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, err
	}
	name, err := packageName(dir)
	if err != nil {
		return false, err
	}
	var buf bytes.Buffer
	err = goFileTemplate.Execute(&buf, map[string]any{
		"Tool":    tool,
		"Format":  goFileFormat,
		"Package": name,
		"Data":    DataDir,
	})
	if err != nil {
		return false, err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return false, err
	}
	var ch changes
	if err := writeIfChanged(file, src, &ch); err != nil {
		return false, err
	}
	return ch.written > 0, nil
}

func goFileVersion(src []byte) int {
	sc := bufio.NewScanner(bytes.NewReader(src))
	for sc.Scan() {
		line := sc.Text()
		if v, ok := strings.CutPrefix(line, goFileMarker); ok {
			var n int
			if _, err := fmt.Sscanf(v, "%d", &n); err == nil {
				return n
			}
			return 0
		}
		if strings.HasPrefix(line, "package ") {
			break
		}
	}
	return 0
}

// packageName берёт имя пакета из соседних файлов или строит его из имени каталога
func packageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return "", err
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || name == GoFile || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.PackageClauseOnly)
		if err != nil {
			return "", err
		}
		return f.Name.Name, nil
	}
	return sanitizePackageName(filepath.Base(dir)), nil
}

func sanitizePackageName(base string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(base) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	name := b.String()
	if name == "" || unicode.IsDigit(rune(name[0])) {
		name = "schemas" + name
	}
	return name
}
