package generate

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

	"crd.tools/crd"
	"crd.tools/crd/validation"
	"crd.tools/gocmd"
)

// crdPackage путь импорта пакета с реестром определений
const crdPackage = "crd.tools/crd"

// tmpDir служебный каталог внутри модуля, Go пропускает каталоги с _ в начале имени
const tmpDir = "_tmp"

// genDir каталог генератора внутри tmpDir, целиком принадлежит генератору
const genDir = "_crdgen"

// staleAge возраст, после которого каталоги упавших запусков удаляются
const staleAge = time.Hour

// fileHeader заголовок сгенерированных манифестов
const fileHeader = "# Code generated by crd. DO NOT EDIT.\n"

// Settings это настройки генератора
type Settings struct {
	// Tool имя инструмента для сообщений
	Tool string

	// Root корень модуля проекта
	Root string

	// SchemasPackage путь импорта пакета со снимками, пусто если снимков нет
	SchemasPackage string
}

// Overrides это значения, которые заменяют заданные в определении CRD
// Применяются, только если выбран ровно один CRD
type Overrides struct {
	Group       string
	Kind        string
	Plural      string
	Singular    string
	Scope       string
	ShortNames  []string
	Categories  []string
	Labels      map[string]string
	Annotations map[string]string
}

// Empty сообщает, что переопределений нет
func (o Overrides) Empty() bool {
	return o.Group == "" && o.Kind == "" && o.Plural == "" && o.Singular == "" && o.Scope == "" &&
		len(o.ShortNames) == 0 && len(o.Categories) == 0 && len(o.Labels) == 0 && len(o.Annotations) == 0
}

// Filter отбирает определения по полям, пустое поле не фильтрует
// Сравнение точное и с учётом регистра, по значениям из определения до переопределений
type Filter struct {
	Kind   string
	Group  string
	Plural string
}

// Empty сообщает, что фильтр пустой
func (f Filter) Empty() bool {
	return f.Kind == "" && f.Group == "" && f.Plural == ""
}

// String описывает фильтр для сообщений
func (f Filter) String() string {
	var parts []string
	if f.Kind != "" {
		parts = append(parts, "kind="+f.Kind)
	}
	if f.Group != "" {
		parts = append(parts, "group="+f.Group)
	}
	if f.Plural != "" {
		parts = append(parts, "plural="+f.Plural)
	}
	return strings.Join(parts, ", ")
}

// Options это параметры одного запуска
type Options struct {
	// Dir каталог, относительно которого разрешаются шаблоны
	Dir string

	// Patterns шаблоны пакетов, по умолчанию .
	Patterns []string

	// Filter отбирает определения
	Filter Filter

	// Overrides переопределения для единственного выбранного CRD
	Overrides Overrides

	// Output каталог для файлов, пусто — вывод в Stdout
	Output string

	// Validate включает проверку каждого CRD кодом API-сервера перед выводом
	Validate bool

	// Stdout поток для манифестов без Output
	Stdout io.Writer

	// Stderr поток для предупреждений
	Stderr io.Writer
}

// Report это итог запуска
type Report struct {
	// Packages пакеты с вызовами crd.Add в init
	Packages []string

	// CRDs число собранных CRD
	CRDs int

	// Files записанные файлы, пусто при выводе в Stdout
	Files []string
}

// Engine собирает манифесты CRD из определений, добавленных через crd.Add
type Engine struct {
	s Settings
}

// New возвращает генератор
func New(s Settings) (*Engine, error) {
	if s.Tool == "" || s.Root == "" {
		return nil, errors.New("generate: empty tool name or module root")
	}
	return &Engine{s: s}, nil
}

// Run находит определения, собирает CRD, при Validate проверяет их и пишет манифесты
func (e *Engine) Run(ctx context.Context, opts Options) (Report, error) {
	report, results, err := e.collect(ctx, opts)
	if err != nil {
		return report, err
	}
	objs, err := checkResults(ctx, results, opts.Validate)
	if err != nil {
		return report, err
	}
	report.CRDs = len(objs)
	if opts.Output == "" {
		return report, writeStdout(opts.Stdout, objs)
	}
	report.Files, err = writeFiles(opts.Output, opts.Stderr, objs)
	return report, err
}

// Row это строка списка определений
type Row struct {
	// Name имя CRD: plural.group
	Name string

	// Kind вид ресурса
	Kind string

	// Group группа API
	Group string

	// Plural имя ресурса во множественном числе
	Plural string

	// Scope область видимости
	Scope string

	// Versions версии в порядке определения
	Versions []string

	// Storage версия хранения
	Storage string

	// Error ошибка сборки или, с Validate, проверки, пусто если всё в порядке
	Error string
}

// List находит определения и возвращает их заголовки
// Ошибки отдельных CRD попадают в строки, а не прерывают список
func (e *Engine) List(ctx context.Context, opts Options) ([]Row, error) {
	_, results, err := e.collect(ctx, opts)
	if err != nil {
		return nil, err
	}
	rows := make([]Row, 0, len(results))
	for _, r := range results {
		row := Row{Kind: r.Kind, Group: r.Group, Plural: r.Plural, Error: r.Error}
		if r.Group != "" && r.Plural != "" {
			row.Name = r.Plural + "." + r.Group
		}
		if r.Error == "" {
			obj := &apiextv1.CustomResourceDefinition{}
			if err := json.Unmarshal(r.CRD, obj); err != nil {
				row.Error = "decode: " + err.Error()
			} else {
				row.Name = obj.Name
				row.Scope = string(obj.Spec.Scope)
				for _, v := range obj.Spec.Versions {
					row.Versions = append(row.Versions, v.Name)
					if v.Storage {
						row.Storage = v.Name
					}
				}
				if opts.Validate {
					if err := validation.Validate(ctx, obj); err != nil {
						row.Error = err.Error()
					}
				}
			}
		}
		rows = append(rows, row)
	}
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].Group != rows[j].Group {
			return rows[i].Group < rows[j].Group
		}
		return rows[i].Plural < rows[j].Plural
	})
	return rows, nil
}

// discover находит пакеты с определениями по шаблонам
func (e *Engine) discover(ctx context.Context, opts Options) (Report, error) {
	if len(opts.Patterns) == 0 {
		opts.Patterns = []string{"."}
	}
	pkgs, err := Discover(ctx, opts.Dir, opts.Patterns)
	if err != nil {
		return Report{}, err
	}
	report := Report{Packages: pkgs}
	if len(pkgs) == 0 {
		return report, fmt.Errorf("no crd.Add calls in init found in %s", strings.Join(opts.Patterns, " "))
	}
	return report, nil
}

// OpenAPISettings это настройки документа OpenAPI
type OpenAPISettings struct {
	Title    string
	Version  string
	Prefixes []Prefix
}

// Prefix это замена начала имени компонента
type Prefix struct {
	From string
	To   string
}

// OpenAPI находит определения и строит по ним документ OpenAPI v3 в JSON
func (e *Engine) OpenAPI(ctx context.Context, opts Options, settings OpenAPISettings) ([]byte, error) {
	report, err := e.discover(ctx, opts)
	if err != nil {
		return nil, err
	}
	out, err := e.runMain(ctx, renderOpenAPIMain(e.s.SchemasPackage, report.Packages, opts.Filter, settings))
	if err != nil {
		return nil, err
	}
	var res struct {
		Fatal string          `json:"fatal"`
		Doc   json.RawMessage `json:"doc"`
	}
	if err := json.Unmarshal(out, &res); err != nil {
		return nil, fmt.Errorf("decode generator output: %w", err)
	}
	if res.Fatal != "" {
		return nil, errors.New(res.Fatal)
	}
	return res.Doc, nil
}

// collect находит пакеты, запускает временный main и возвращает результаты сборки
func (e *Engine) collect(ctx context.Context, opts Options) (Report, []result, error) {
	report, err := e.discover(ctx, opts)
	if err != nil {
		return report, nil, err
	}
	pkgs := report.Packages

	src := renderMain(e.s.SchemasPackage, pkgs, opts.Filter, opts.Overrides)
	out, err := e.runMain(ctx, src)
	if err != nil {
		return report, nil, err
	}
	var res output
	if err := json.Unmarshal(out, &res); err != nil {
		return report, nil, fmt.Errorf("decode generator output: %w", err)
	}
	if res.Fatal != "" {
		return report, nil, errors.New(res.Fatal)
	}
	if len(res.Results) == 0 {
		if opts.Filter.Empty() {
			return report, nil, errors.New("no CRD definitions found")
		}
		return report, nil, fmt.Errorf("no CRD matches %s", opts.Filter)
	}
	return report, res.Results, nil
}

// output это то, что пишет временный main
type output struct {
	Fatal   string   `json:"fatal,omitempty"`
	Results []result `json:"results"`
}

type result struct {
	Kind   string          `json:"kind"`
	Group  string          `json:"group"`
	Plural string          `json:"plural"`
	CRD    json.RawMessage `json:"crd,omitempty"`
	Error  string          `json:"error,omitempty"`
	Code   int             `json:"code,omitempty"`
}

// checkResults разбирает собранные CRD и, если validate, проверяет их кодом API-сервера
func checkResults(ctx context.Context, results []result, validate bool) ([]*apiextv1.CustomResourceDefinition, error) {
	var errs []string
	objs := make([]*apiextv1.CustomResourceDefinition, 0, len(results))
	for _, r := range results {
		if r.Error != "" {
			errs = append(errs, fmt.Sprintf("%s: %s", r.Kind, r.Error))
			continue
		}
		obj := &apiextv1.CustomResourceDefinition{}
		if err := json.Unmarshal(r.CRD, obj); err != nil {
			errs = append(errs, fmt.Sprintf("%s: decode: %s", r.Kind, err))
			continue
		}
		if validate {
			if err := validation.Validate(ctx, obj); err != nil {
				errs = append(errs, fmt.Sprintf("%s: %s", obj.Name, err))
				continue
			}
		}
		objs = append(objs, obj)
	}
	if len(errs) > 0 {
		return nil, errors.New("crd generate:\n  " + strings.Join(errs, "\n  "))
	}
	// стабильный порядок вывода, при совпадении ключей — порядок добавления
	sort.SliceStable(objs, func(i, j int) bool {
		a, b := objs[i].Spec, objs[j].Spec
		if a.Group != b.Group {
			return a.Group < b.Group
		}
		return a.Names.Plural < b.Names.Plural
	})
	return objs, nil
}

func writeStdout(w io.Writer, objs []*apiextv1.CustomResourceDefinition) error {
	for _, obj := range objs {
		data, err := crd.Marshal(obj)
		if err != nil {
			return err
		}
		if _, err := w.Write(data); err != nil {
			return err
		}
	}
	return nil
}

// writeFiles пишет по файлу на CRD с именем <group>_<plural>.yaml
// При совпадении имён добавляет _1, _2 и предупреждает в stderr
// Существующие файлы перезаписываются, чужие файлы в каталоге не трогаются
func writeFiles(dir string, stderr io.Writer, objs []*apiextv1.CustomResourceDefinition) ([]string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	used := map[string]int{}
	var files []string
	for _, obj := range objs {
		base := obj.Spec.Group + "_" + obj.Spec.Names.Plural
		name := base
		if n := used[base]; n > 0 {
			name = fmt.Sprintf("%s_%d", base, n)
			fmt.Fprintf(stderr, "warning: %s.yaml already written, %s has the same name %s, saved as %s.yaml\n",
				base, obj.Spec.Names.Kind, obj.Name, name)
		}
		used[base]++

		data, err := crd.Marshal(obj)
		if err != nil {
			return files, err
		}
		file := filepath.Join(dir, name+".yaml")
		if err := os.WriteFile(file, append([]byte(fileHeader), data...), 0o644); err != nil {
			return files, err
		}
		files = append(files, file)
	}
	return files, nil
}

// Discover находит пакеты, в которых crd.Add вызывается в init
// Вызовы вне init не учитываются: они не гарантированно выполнятся до запуска main
func Discover(ctx context.Context, dir string, patterns []string) ([]string, error) {
	pkgs, err := gocmd.List(ctx, dir, patterns...)
	if err != nil {
		return nil, err
	}
	var errs []string
	var out []string
	quick := []byte(strconv.Quote(crdPackage))
	for _, pkg := range pkgs {
		if pkg.Error != nil {
			errs = append(errs, pkg.Error.Err)
			continue
		}
		// пакет main нельзя импортировать из временного main
		if pkg.Name == "main" {
			continue
		}
		found, err := hasAddInInit(pkg.Dir, pkg.GoFiles, quick)
		if err != nil {
			return nil, err
		}
		if found {
			out = append(out, pkg.ImportPath)
		}
	}
	if len(errs) > 0 {
		return nil, errors.New("go list:\n  " + strings.Join(errs, "\n  "))
	}
	sort.Strings(out)
	return out, nil
}

func hasAddInInit(dir string, files []string, quick []byte) (bool, error) {
	fset := token.NewFileSet()
	for _, name := range files {
		file := filepath.Join(dir, name)
		data, err := os.ReadFile(file)
		if err != nil {
			return false, err
		}
		if !bytes.Contains(data, quick) {
			continue
		}
		f, err := parser.ParseFile(fset, file, data, parser.SkipObjectResolution)
		if err != nil {
			return false, err
		}
		alias := crdAlias(f)
		if alias == "" {
			continue
		}
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || fn.Name.Name != "init" || fn.Body == nil {
				continue
			}
			if callsAdd(fn.Body, alias) {
				return true, nil
			}
		}
	}
	return false, nil
}

// crdAlias возвращает имя, под которым в файле импортирован пакет crd
func crdAlias(f *ast.File) string {
	for _, spec := range f.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil || path != crdPackage {
			continue
		}
		if spec.Name == nil {
			return "crd"
		}
		if spec.Name.Name == "_" || spec.Name.Name == "." {
			return ""
		}
		return spec.Name.Name
	}
	return ""
}

func callsAdd(body *ast.BlockStmt, alias string) bool {
	found := false
	ast.Inspect(body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || found {
			return !found
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Add" {
			return true
		}
		if x, ok := sel.X.(*ast.Ident); ok && x.Name == alias {
			found = true
		}
		return !found
	})
	return found
}

// runMain пишет временный main в _tmp/_crdgen/<id> и запускает его в модуле проекта
func (e *Engine) runMain(ctx context.Context, src []byte) ([]byte, error) {
	tmp := filepath.Join(e.s.Root, tmpDir)
	_, err := os.Stat(tmp)
	createdTmp := errors.Is(err, os.ErrNotExist)
	gen := filepath.Join(tmp, genDir)
	if err := os.MkdirAll(gen, 0o755); err != nil {
		return nil, err
	}
	removeStale(gen)
	dir, err := os.MkdirTemp(gen, "run")
	if err != nil {
		return nil, err
	}
	defer func() {
		os.RemoveAll(dir)
		os.Remove(gen) // удаляется, только если пуст
		if createdTmp {
			os.Remove(tmp)
		}
	}()
	if err := os.WriteFile(filepath.Join(dir, "main.go"), src, 0o644); err != nil {
		return nil, err
	}

	rel, err := filepath.Rel(e.s.Root, dir)
	if err != nil {
		return nil, err
	}
	cmd := exec.CommandContext(ctx, "go", "run", "./"+filepath.ToSlash(rel))
	cmd.Dir = e.s.Root
	cmd.Env = gocmd.Environ()
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg == "" {
			msg = err.Error()
		}
		return nil, fmt.Errorf("run generator: %s", msg)
	}
	return stdout.Bytes(), nil
}

// removeStale удаляет каталоги упавших запусков
func removeStale(gen string) {
	entries, err := os.ReadDir(gen)
	if err != nil {
		return
	}
	for _, e := range entries {
		info, err := e.Info()
		if err != nil || !e.IsDir() || time.Since(info.ModTime()) < staleAge {
			continue
		}
		os.RemoveAll(filepath.Join(gen, e.Name()))
	}
}
