package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// renderMain пишет исходник временного main
// Пакеты с определениями импортируются ради их init, в котором вызывается crd.Add
func renderMain(schemasPkg string, pkgs []string, f Filter, o Overrides) []byte {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("// Code generated by crd generate. DO NOT EDIT.\n\n")
	w("package main\n\n")
	w("import (\n\t\"encoding/json\"\n\t\"os\"\n")
	if !o.Empty() {
		w("\t\"strconv\"\n")
	}
	w("\n\t\"crd.tools/crd\"\n")
	if schemasPkg != "" {
		w("\tschemas %s\n", strconv.Quote(schemasPkg))
	}
	for _, p := range pkgs {
		w("\t_ %s\n", strconv.Quote(p))
	}
	w(")\n\n")

	w(`type result struct {
	Kind   string          ` + "`json:\"kind\"`" + `
	Group  string          ` + "`json:\"group\"`" + `
	Plural string          ` + "`json:\"plural\"`" + `
	CRD   json.RawMessage ` + "`json:\"crd,omitempty\"`" + `
	Error string          ` + "`json:\"error,omitempty\"`" + `
	Code  int             ` + "`json:\"code,omitempty\"`" + `
}

type output struct {
	Fatal   string   ` + "`json:\"fatal,omitempty\"`" + `
	Results []result ` + "`json:\"results\"`" + `
}

func main() {
`)
	if schemasPkg != "" {
		w("\tcrd.SetDERSource(schemas.FS())\n")
	}
	w("\tvar selected []crd.CRD\n")
	w("\tfor _, c := range crd.List() {\n")
	if f.Kind != "" {
		w("\t\tif c.GroupVersionKind(\"\").Kind != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Kind))
	}
	if f.Group != "" {
		w("\t\tif c.GroupVersionKind(\"\").Group != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Group))
	}
	if f.Plural != "" {
		w("\t\tif c.GroupVersionResource(\"\").Resource != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Plural))
	}
	w("\t\tselected = append(selected, c)\n\t}\n")

	if !o.Empty() {
		w("\tif len(selected) != 1 {\n")
		w("\t\tjson.NewEncoder(os.Stdout).Encode(output{Fatal: %s})\n",
			`"overrides need exactly one CRD, selected: " + strconv.Itoa(len(selected)) + ", narrow the selection with --kind, --group or --plural"`)
		w("\t\treturn\n\t}\n")
		w("\tc := selected[0]\n")
		for _, call := range overrideCalls(o) {
			w("\tc.%s\n", call)
		}
	}
	w(`	var res output
	for _, c := range selected {
		gvk := c.GroupVersionKind("")
		r := result{Kind: gvk.Kind, Group: gvk.Group, Plural: c.GroupVersionResource("").Resource}
		obj, err := c.Build()
		if err != nil {
			r.Error = err.Error()
			r.Code = int(crd.Code(err))
		} else {
			r.CRD, _ = json.Marshal(obj)
		}
		res.Results = append(res.Results, r)
	}
	json.NewEncoder(os.Stdout).Encode(res)
}
`)
	src, err := format.Source(b.Bytes())
	if err != nil {
		// шаблон собран из литералов, ошибка форматирования — ошибка генератора
		panic(fmt.Sprintf("generate: format main: %v\n%s", err, b.String()))
	}
	return src
}

// overrideCalls возвращает вызовы методов CRD для переопределений в стабильном порядке
func overrideCalls(o Overrides) []string {
	var calls []string
	add := func(method, value string) {
		if value != "" {
			calls = append(calls, fmt.Sprintf("%s(%s)", method, strconv.Quote(value)))
		}
	}
	add("Group", o.Group)
	add("Kind", o.Kind)
	add("Plural", o.Plural)
	add("Singular", o.Singular)
	add("Scope", o.Scope)
	if len(o.ShortNames) > 0 {
		calls = append(calls, "ShortNames("+quoteAll(o.ShortNames)+")")
	}
	if len(o.Categories) > 0 {
		calls = append(calls, "Categories("+quoteAll(o.Categories)+")")
	}
	for _, k := range sortedKeys(o.Labels) {
		calls = append(calls, fmt.Sprintf("Label(%s, %s)", strconv.Quote(k), strconv.Quote(o.Labels[k])))
	}
	for _, k := range sortedKeys(o.Annotations) {
		calls = append(calls, fmt.Sprintf("Annotation(%s, %s)", strconv.Quote(k), strconv.Quote(o.Annotations[k])))
	}
	return calls
}

func quoteAll(values []string) string {
	q := make([]string, len(values))
	for i, v := range values {
		q[i] = strconv.Quote(v)
	}
	return strings.Join(q, ", ")
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// renderOpenAPIMain пишет исходник временного main, который строит документ OpenAPI
func renderOpenAPIMain(schemasPkg string, pkgs []string, f Filter, settings OpenAPISettings) []byte {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("// Code generated by crd openapi. DO NOT EDIT.\n\n")
	w("package main\n\n")
	w("import (\n\t\"encoding/json\"\n\t\"os\"\n\n\t\"crd.tools/crd\"\n")
	if schemasPkg != "" {
		w("\tschemas %s\n", strconv.Quote(schemasPkg))
	}
	for _, p := range pkgs {
		w("\t_ %s\n", strconv.Quote(p))
	}
	w(")\n\n")
	w(`type output struct {
	Fatal string          ` + "`json:\"fatal,omitempty\"`" + `
	Doc   json.RawMessage ` + "`json:\"doc,omitempty\"`" + `
}

func fail(msg string) {
	json.NewEncoder(os.Stdout).Encode(output{Fatal: msg})
}

func main() {
`)
	if schemasPkg != "" {
		w("\tcrd.SetDERSource(schemas.FS())\n")
	}
	w("\tvar selected []crd.CRD\n")
	w("\tfor _, c := range crd.List() {\n")
	writeFilter(w, f)
	w("\t\tselected = append(selected, c)\n\t}\n")
	w("\tif len(selected) == 0 {\n\t\tfail(%s)\n\t\treturn\n\t}\n", strconv.Quote("no CRD definitions found"))
	w("\tdoc, err := crd.OpenAPI(crd.OpenAPIConfig{\n")
	w("\t\tTitle: %s,\n\t\tVersion: %s,\n", strconv.Quote(settings.Title), strconv.Quote(settings.Version))
	w("\t\tPrefixes: []crd.Prefix{\n")
	for _, p := range settings.Prefixes {
		w("\t\t\t{From: %s, To: %s},\n", strconv.Quote(p.From), strconv.Quote(p.To))
	}
	w("\t\t},\n\t}, selected...)\n")
	w(`	if err != nil {
		fail(err.Error())
		return
	}
	data, err := doc.JSON()
	if err != nil {
		fail(err.Error())
		return
	}
	json.NewEncoder(os.Stdout).Encode(output{Doc: data})
}
`)
	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(fmt.Sprintf("generate: format openapi main: %v\n%s", err, b.String()))
	}
	return src
}

// writeFilter пишет проверки фильтра внутри цикла по определениям
func writeFilter(w func(string, ...any), f Filter) {
	if f.Kind != "" {
		w("\t\tif c.GroupVersionKind(\"\").Kind != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Kind))
	}
	if f.Group != "" {
		w("\t\tif c.GroupVersionKind(\"\").Group != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Group))
	}
	if f.Plural != "" {
		w("\t\tif c.GroupVersionResource(\"\").Resource != %s {\n\t\t\tcontinue\n\t\t}\n", strconv.Quote(f.Plural))
	}
}
